"""Public tau2-free stakeholder configuration and private world-model API."""

# The workspace-level auxiliary Pyright runner can miss freshly added sibling
# modules; project-level ``uv run pyright`` remains the authoritative check.
# pyright: reportMissingImports=false

from .addressing import (
    AddressKind,
    InvalidSemanticAddressError,
    NodeAddressProperty,
    ParsedSemanticAddress,
    ResolvedSemanticAddress,
    SemanticAddressError,
    UnknownSemanticAddressError,
    parse_semantic_address,
    resolve_semantic_address,
    try_resolve_semantic_address,
)
from .config import (
    ConceptKnowledgeOverride,
    EdgeProperty,
    ForgettingConfig,
    NodeProperty,
    StakeholderFilter,
    StakeholderForgettingConfig,
    StakeholderProfile,
)
from .knowledge import (
    DONT_KNOW,
    KnowledgeConceptRef,
    KnowledgeDontKnowType,
    KnowledgeEdgeKind,
    KnowledgeListSlot,
    KnowledgeSlot,
    ShortcutProvenance,
    StakeholderEdge,
    StakeholderKnowledge,
    StakeholderKnowledgeConcept,
    StakeholderKnowledgeGraph,
    StakeholderNode,
    is_dont_know,
    is_known_absent,
    validate_stakeholder_knowledge,
    validate_stakeholder_knowledge_graph,
)
from .projection import (
    KnowledgeProjectionError,
    derive_knowledge_coverage_view,
    knowledge_coverage_view,
    project_knowledge,
)
from .prompting import render_knowledge_prompt
from .response import (
    AlignmentAct,
    ConceptAlignmentAssertion,
    PlannedResponseItem,
    ResponseParseError,
    ResponseValidationError,
    SemanticAnnotation,
    SemanticMode,
    SemanticResponsePlan,
    StakeholderResponse,
    TerminologyConfirmation,
    canonical_semantic_mode,
    parse_semantic_response_plan,
    parse_stakeholder_response,
    semantic_mode_for_resolution,
    validate_response_plan,
    validate_stakeholder_response,
    validate_terminology_provenance,
)

__all__ = [
    "AddressKind",
    "AlignmentAct",
    "ConceptAlignmentAssertion",
    "ConceptKnowledgeOverride",
    "DONT_KNOW",
    "EdgeProperty",
    "ForgettingConfig",
    "InvalidSemanticAddressError",
    "KnowledgeProjectionError",
    "KnowledgeConceptRef",
    "KnowledgeDontKnowType",
    "KnowledgeEdgeKind",
    "KnowledgeListSlot",
    "KnowledgeSlot",
    "NodeAddressProperty",
    "NodeProperty",
    "ParsedSemanticAddress",
    "PlannedResponseItem",
    "ResolvedSemanticAddress",
    "ResponseParseError",
    "ResponseValidationError",
    "SemanticAddressError",
    "SemanticAnnotation",
    "SemanticMode",
    "SemanticResponsePlan",
    "ShortcutProvenance",
    "StakeholderEdge",
    "StakeholderFilter",
    "StakeholderForgettingConfig",
    "StakeholderKnowledge",
    "StakeholderKnowledgeConcept",
    "StakeholderKnowledgeGraph",
    "StakeholderNode",
    "StakeholderResponse",
    "StakeholderProfile",
    "TerminologyConfirmation",
    "UnknownSemanticAddressError",
    "canonical_semantic_mode",
    "is_dont_know",
    "is_known_absent",
    "knowledge_coverage_view",
    "parse_semantic_response_plan",
    "parse_stakeholder_response",
    "derive_knowledge_coverage_view",
    "parse_semantic_address",
    "project_knowledge",
    "render_knowledge_prompt",
    "resolve_semantic_address",
    "semantic_mode_for_resolution",
    "try_resolve_semantic_address",
    "validate_response_plan",
    "validate_terminology_provenance",
    "validate_stakeholder_knowledge",
    "validate_stakeholder_response",
    "validate_stakeholder_knowledge_graph",
]
