"""Compatibility exports for pure AgentGraph mutation operations.

The implementation lives one package level up so runtime contracts and graph
models do not form an import cycle.  This module remains core-only.
"""

# The workspace-level auxiliary resolver may not see freshly added siblings;
# project-level ``uv run pyright`` is authoritative for this package.
# pyright: reportMissingImports=false

from ..graph_mutations import (
    GraphMutationError,
    add_agent_concept,
    add_agent_edge,
    add_agent_node,
    add_concept,
    add_edge,
    add_graph_edge,
    add_graph_node,
    add_node,
    attach_evidence,
    attach_evidence_ref,
    define_agent_concept,
    define_concept,
    define_graph_concept,
    remove_agent_concept,
    remove_agent_edge,
    remove_agent_node,
    remove_concept,
    remove_edge,
    remove_graph_concept,
    remove_graph_edge,
    remove_graph_node,
    remove_node,
    set_agent_edge_condition,
    set_agent_node_property,
    set_edge_condition,
    set_edge_condition_absent,
    set_edge_condition_dont_know,
    set_edge_slot,
    set_end_nodes,
    set_node_absent,
    set_node_dont_know,
    set_node_property,
    set_node_slot,
    set_start_nodes,
    update_agent_concept,
    update_agent_edge,
    update_agent_node,
    update_concept,
    update_edge,
    update_graph_concept,
    update_graph_edge,
    update_graph_node,
    update_node,
)

__all__ = [
    "GraphMutationError",
    "add_agent_concept",
    "add_agent_edge",
    "add_agent_node",
    "add_concept",
    "add_edge",
    "add_graph_edge",
    "add_graph_node",
    "add_node",
    "attach_evidence",
    "attach_evidence_ref",
    "define_agent_concept",
    "define_concept",
    "define_graph_concept",
    "remove_agent_concept",
    "remove_agent_edge",
    "remove_agent_node",
    "remove_concept",
    "remove_edge",
    "remove_graph_concept",
    "remove_graph_edge",
    "remove_graph_node",
    "remove_node",
    "set_agent_edge_condition",
    "set_agent_node_property",
    "set_edge_condition",
    "set_edge_condition_absent",
    "set_edge_condition_dont_know",
    "set_edge_slot",
    "set_end_nodes",
    "set_node_absent",
    "set_node_dont_know",
    "set_node_property",
    "set_node_slot",
    "set_start_nodes",
    "update_agent_concept",
    "update_agent_edge",
    "update_agent_node",
    "update_concept",
    "update_edge",
    "update_graph_concept",
    "update_graph_edge",
    "update_graph_node",
    "update_node",
]
